#
# secrets.RELEASE_NOTES_ASSISTANT_TOKEN issued by https://code.forgejo.org/release-notes-assistant-bot with write:issue, write:repository, write:organization and member of the https://code.forgejo.org/org/forgejo/teams/release-notes-assistant team that further tune the access
#
name: issue-labels

on:
  pull_request_target:
    types:
      - edited
      - synchronize
      - labeled

env:
  RNA_VERSION: v1.4.0 # renovate: datasource=forgejo-releases depName=forgejo/release-notes-assistant registryUrl=https://code.forgejo.org

jobs:
  debug:
    runs-on: docker
    steps:
      - name: event
        run: |
          cat <<'EOF'
          ${{ toJSON(forge) }}
          EOF
  release-notes:
    if: vars.ROLE == 'forgejo-coding' && !contains(forge.event.pull_request.labels.*.name, 'Kind/DependencyUpdate')
    runs-on: docker
    container:
      image: 'data.forgejo.org/oci/ci:1'
    steps:
      - uses: https://data.forgejo.org/actions/checkout@v4

      - name: event
        run: |
          cat <<'EOF'
          ${{ toJSON(forge.event.pull_request.labels.*.name) }}
          EOF
          cat <<'EOF'
          ${{ toJSON(forge.event) }}
          EOF

      - name: install release-notes-assistant
        run: |
          set -x
          wget -O /usr/local/bin/rna https://code.forgejo.org/forgejo/release-notes-assistant/releases/download/${{ env.RNA_VERSION}}/release-notes-assistant
          chmod +x /usr/local/bin/rna

      - name: release-notes-assistant preview
        run: |
          rna --verbose --storage pr --storage-location ${{ forge.event.pull_request.number }}  --forgejo-url $FORGEJO_SERVER_URL --repository $FORGEJO_REPOSITORY --token ${{ secrets.RELEASE_NOTES_ASSISTANT_TOKEN }} preview ${{ forge.event.pull_request.number }}
