// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewMockPoller creates a new instance of MockPoller. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPoller(t interface {
	mock.TestingT
	Cleanup(func())
},
) *MockPoller {
	if helper, ok := t.(interface{ Helper() }); ok {
		helper.Helper()
	}

	mock := &MockPoller{}
	mock.Mock.Test(t)

	t.Cleanup(func() {
		if helper, ok := t.(interface{ Helper() }); ok {
			helper.Helper()
		}
		mock.AssertExpectations(t)
	})

	return mock
}

// MockPoller is an autogenerated mock type for the Poller type
type MockPoller struct {
	mock.Mock
}

type MockPoller_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPoller) EXPECT() *MockPoller_Expecter {
	return &MockPoller_Expecter{mock: &_m.Mock}
}

// Poll provides a mock function for the type MockPoller
func (_mock *MockPoller) Poll() {
	_mock.Called()
	return
}

// MockPoller_Poll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Poll'
type MockPoller_Poll_Call struct {
	*mock.Call
}

// Poll is a helper method to define mock.On call
func (_e *MockPoller_Expecter) Poll() *MockPoller_Poll_Call {
	return &MockPoller_Poll_Call{Call: _e.mock.On("Poll")}
}

func (_c *MockPoller_Poll_Call) Run(run func()) *MockPoller_Poll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPoller_Poll_Call) Return() *MockPoller_Poll_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPoller_Poll_Call) RunAndReturn(run func()) *MockPoller_Poll_Call {
	_c.Run(run)
	return _c
}

// Shutdown provides a mock function for the type MockPoller
func (_mock *MockPoller) Shutdown(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPoller_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockPoller_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockPoller_Expecter) Shutdown(ctx any) *MockPoller_Shutdown_Call {
	return &MockPoller_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockPoller_Shutdown_Call) Run(run func(ctx context.Context)) *MockPoller_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPoller_Shutdown_Call) Return(err error) *MockPoller_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPoller_Shutdown_Call) RunAndReturn(run func(ctx context.Context) error) *MockPoller_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}
